added parameters
Brigade-2/dating-app-backend pull request #24
Opened 2022-10-18 16:31 UTC by GeorgySmirnoff

2022-10-18 16:54 UTC, fedos3d requested changes

2022-10-18 17:03 UTC, fedos3d requested changes

2022-10-18 17:03 UTC, fedos3d commented on .github/workflows/build_deploy.yml
> +          docker image rm ${{ github.event.repository.name }}-${{ github.head_ref }} &> /dev/null || true
Тут наверн лучше использовать wildcard по типу 
`${{ github.event.repository.name }}-*`. Ведь если там будут новые пры, то эти штуки буду плодится, а из никто не убьет, хотя сложно сказать как лучше сделать, но иметь больше одного тестового контейнера крутящегося точно нельзя. Так что вроде валидный коммент.

2022-10-30 11:41 UTC, GeorgySmirnoff commented on .github/workflows/build_deploy.yml
> +          docker image rm ${{ github.event.repository.name }}-${{ github.head_ref }} &> /dev/null || true
Окес , тогда в пайпе для прода надо по другому называть контейнеры

2022-10-30 19:02 UTC, fedos3d commented on .github/workflows/build_deploy.yml
> +          docker image rm ${{ github.event.repository.name }}-${{ github.head_ref }} &> /dev/null || true
Так ты же не поправил, там ведь при создании нового пра, старый контейнер не погасится и порт не освободится, надо переделать нейминг контейнеров на просто *-test

2022-10-31 19:05 UTC, fedos3d commented
Вроде кошер, аппрув!

2022-10-31 19:06 UTC, fedos3d approved these changes

2022-10-31 19:22 UTC, fedos3d requested changes
Тупанул слегка, надо бы коммиты засквошить, чтобы мастер не засирать, засквошишь? Тут норм пример есть(самый залайканный комм): https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together И помни, что там придется force пуш делать после этого.

2022-11-28 21:37 UTC, fedos3d approved these changes

2022-11-28 21:44 UTC, merged